# These are supported funding model platforms

github: boldbat          # Replace with up to 4 GitHub Sponsors-eligible usernames
# patreon: user          # Replace with a single Patreon username
# open_collective: user  # Replace with a single Open Collective username
# ko_fi: user            # Replace with a single Ko-fi username
# custom: ['https://oyu-intelligence.com'] # Replace with up to 4 custom sponsorship URLs
